version: "3.2"

networks:
  stack:

volumes:
  apiportal-data:

services:

  apigateway:
    image: store/softwareag/apigateway-trial:10.11
    ports:
      - "5555:5555"
      - "9072:9072"
    hostname: apigateway
    networks:
      - stack

  apigateway_configurator:
    image: sagdevops-ansible-apigateway-sample-configurator:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_ANSIBLE_IMAGE: ${REG}sagdevops-ansible-apigateway:latest
    environment: 
      env_apigateway_protocol: http
      env_apigateway_host: apigateway
      env_apigateway_port: "5555"
      env_apigateway_rest_user: Administrator
      env_apigateway_rest_password: "somethingnew"
      env_apigateway_rest_password_old: "manage"
      env_apigateway_configure_default_ignore_errors: "false"
      env_apigateway_configure_portalgateway_ignore_errors: "true"
      env_apigateway_configure_apis_publish_groups_ignore_errors: "true"
      env_apigateway_configure_packages_publish_groups_ignore_errors: "true"
      env_apigateway_lb_http_url: "http://localhost"
      env_apigateway_lb_https_url: "https://localhost"
      env_apigateway_lb_websocket_url: "ws://localhost"
      env_apigateway_lb_http_url_alt1: "http://external_access"
      env_apigateway_lb_https_url_alt1: "https://external_access"
      env_apigateway_lb_websocket_url_alt1: "ws://external_access"
      env_apigateway_lb_webapp_url: "http://external_access"
      env_apigateway_portalgateway_gateway_url: "http://apigateway:5555"
      env_apigateway_portalgateway_gateway_username: "Administrator"
      env_apigateway_portalgateway_gateway_password: "somethingnew"
      env_apigateway_portalgateway_portaltype: devportal
      env_apigateway_portalgateway_apiportal_tenant: default
      env_apigateway_portalgateway_apiportal_url: http://apiportal:18101
      env_apigateway_portalgateway_apiportal_username: system
      env_apigateway_portalgateway_apiportal_password: manager
      env_apigateway_portalgateway_devportal_tenant: default
      env_apigateway_portalgateway_devportal_url: "http://apiportal:18101/portal"
      env_apigateway_portalgateway_devportal_username: "Administrator"
      env_apigateway_portalgateway_devportal_password: "manage"
      env_apigateway_aliases_bookstore_endpoint: http://webmethods-sample-apis-bookstore:7071
      env_apigateway_aliases_uszip_endpoint: http://webmethods-sample-apis-uszip:7071
    networks:
      - stack