---

## certs
### keystore
vars_apigateway_keystore_filepath: "{{ envvars_apigateway_keystore_filepath }}"
vars_apigateway_keystore_filename: "{{ vars_apigateway_keystore_filepath | basename }}"
vars_apigateway_keystore_aliasname: "{{ (vars_apigateway_keystore_filename | splitext)[0] }}"
vars_apigateway_keystore_description: "SAG Keystore"
vars_apigateway_keystore_type: "JKS"
vars_apigateway_keystore_provider: "SUN"
vars_apigateway_keystore_password: "{{ envvars_apigateway_keystore_password }}"
vars_apigateway_keystore_keyalias: "{{ envvars_apigateway_keystore_keyalias }}"
vars_apigateway_keystore_keyalias_password: "{{ envvars_apigateway_keystore_keyalias_password }}"

### truststore
vars_apigateway_truststore_filepath: "{{envvars_apigateway_truststore_filepath }}"
vars_apigateway_truststore_filename: "{{ vars_apigateway_truststore_filepath | basename }}"
vars_apigateway_truststore_aliasname: "{{ (vars_apigateway_truststore_filename | splitext)[0] }}"
vars_apigateway_truststore_description: "SAG Truststore"
vars_apigateway_truststore_type: "JKS"
vars_apigateway_truststore_provider: "SUN"
vars_apigateway_truststore_password: "{{ envvars_apigateway_truststore_password }}"

## apigateway truststore details
vars_apigateway_truststore:
  keyStoreName: "{{ vars_apigateway_truststore_aliasname }}"
  keyStoreType: "{{ vars_apigateway_truststore_type }}"
  keyStoreProvider: "{{ vars_apigateway_truststore_provider }}"
  keyStorePassword: "{{ vars_apigateway_truststore_password | b64encode }}"
  uploadFileName: "{{ vars_apigateway_truststore_filename }}"
  keyStoreDescription: "{{ vars_apigateway_truststore_description }}"
  fileContent: "@{{ vars_apigateway_truststore_filepath }}"
  isPwdBase64Encoded: "true"

## apigateway keystore details
## pkAliasesList: Comma separated list of alias names in the uploaded keystore file.
## pkPasswordsList: Comma separated list of passwords in the same order as the aliases specified in pkAliasesList. If a particular key alias does not have a password, it is denoted by space.
## nullPKpasswds: Comma separated list of boolean values (true/false) indicating whether the particular alias has a password or not in the same order as the aliases specified in pkAliasesList. For each key alias, true indicates that the key alias does not have a password and false indicates that it does have a password.
vars_apigateway_keystore:
  keyStoreName: "{{ vars_apigateway_keystore_aliasname }}"
  keyStoreType: "{{ vars_apigateway_keystore_type }}"
  keyStoreProvider: "{{ vars_apigateway_keystore_provider }}"
  keyStorePassword: "{{ vars_apigateway_keystore_password | b64encode }}"
  uploadFileName: "{{ vars_apigateway_keystore_filename }}"
  keyStoreDescription: "{{ vars_apigateway_keystore_description }}"
  fileContent: "@{{ vars_apigateway_keystore_filepath }}"
  isPwdBase64Encoded: "true"

# this is for the aliases inside the keystore
vars_apigateway_keystore_keyalias_list:
  - keyStoreName: "{{ vars_apigateway_keystore_aliasname }}"
    nullPKpasswds: "false"
    isPwdBase64Encoded: "false"
    bitarray: "1"
    pkAliasesList: "{{ vars_apigateway_keystore_keyalias }}"
    pkPasswordsList: "{{ vars_apigateway_keystore_keyalias_password }}"

## apigateway keystore/truststore setup for inbound and outbound messages
vars_apigateway_keytruststore_configuration:
  keystoreName: "{{ vars_apigateway_keystore_aliasname }}"
  signingAlias: "{{ vars_apigateway_keystore_keyalias }}"
  truststoreName: "{{ vars_apigateway_truststore_aliasname }}"
  outboundKeystoreName: "{{ vars_apigateway_keystore_aliasname }}"
  outboundKeyAlias: "{{ vars_apigateway_keystore_keyalias }}"
  outboundTruststoreName: "{{ vars_apigateway_truststore_aliasname }}"
