---

- include_tasks: "find_ids.yml"
  vars:
    rvar_object_filters:
      - name: "bookstore"
        version: "1.0"
      - name: "uszip"
        version: "1.0"
      - name: "doesnotexist"
        version: "2.0"
