---

# This get a unique object IDs based on provided human-readable filter object
# rvar_object_filters:
#   name: "some_name1"
#   version: "some_version1"
# Return a rest_response_object_id var of type string (empty string if ID was not found)

- include_tasks: "../search/find_objectids.yml"
  vars:
    _find_object_type: api
    _find_object_filters: "{{ rvar_object_filters }}"
    _find_object_responsefield_id: "id"
    _find_object_responsefield_name: "apiName"
    _find_object_responsefield_version: "apiVersion"

- set_fact:
    rest_response_object_ids: "{{ _found_object_ids }}"

- debug: var=rest_response_object_ids verbosity=1