---

  - name: Get single API by ID
    include_tasks: "get.yml"

  - name: init return var with empty list
    set_fact:
      rest_response_gateway_endpoints: "{{ rest_response_object.gatewayEndPoints | default([]) }}"

  - name: api endpoints found from the rest response
    debug: var=rest_response_gateway_endpoints verbosity=1