---

# This get a unique object IDs based on provided human-readable filter object
# rvar_object_filter:
#   name: "some_name1"
#   version: "some_version1"
# Return a rest_response_object_id var of type string (empty string if ID was not found)

- include_tasks: "find_ids.yml"
  vars:
    rvar_object_filters:
      - "{{ rvar_object_filter }}"

- name: Init the response var
  set_fact:
    rest_response_object_id: ""

- name: set single object id
  set_fact:
    rest_response_object_id: "{{ _found_object_ids | first }}"
  when: _found_object_ids | length > 0

- debug: var=rest_response_object_id verbosity=1