---
## Config files
product_instance_name: "default"
runtime_profile_home: "{{ webmethods_install_dir }}/profiles/IS_{{ product_instance_name }}"
runtime_instance_home: "{{ webmethods_install_dir }}/IntegrationServer/instances/{{ product_instance_name }}"
custom_wrapper_file: "{{ runtime_profile_home }}/configuration/custom_wrapper.conf"
runtime_instance_config_file: "{{ runtime_instance_home }}/config/server.cnf"
webmethods_terracotta_license_path: "{{ webmethods_install_dir }}/common/conf/terracotta-license.key"
apigateway_elasticsearch_config_file: "{{ runtime_instance_home }}/packages/WmAPIGateway/config/resources/elasticsearch/config.properties"
apigateway_kibana_config_file: "{{ runtime_profile_home }}/apigateway/dashboard/config/kibana.yml"
apigateway_ui_configuration_config_file: "{{ runtime_profile_home }}/apigateway/config/uiconfiguration.properties"
apigateway_ui_props_configs_dir: "{{ runtime_profile_home }}/configuration/com.softwareag.platform.config.propsloader"
apigateway_saml_group_mapping_file_path: "{{ runtime_instance_home }}/packages/WmAPIGateway/config/resources/security/saml_groups_mapping.xml"
apigateway_external_configs_source_dir: "{{ runtime_instance_home }}/packages/WmAPIGateway/resources/configuration"
apigateway_external_configs_file_path: "{{ apigateway_external_configs_source_dir }}/custom-configs.yml"
apigateway_external_configs_source_file_path: "{{ apigateway_external_configs_source_dir }}/config-sources.yml"
configs_enabled: true

apigateway_base_uri: "http://localhost:9072"
apigateway_base_path: "{{ apigateway_base_uri }}/apigatewayui"
apigateway_samlsso_autogenerated_metadata_url: "{{ apigateway_base_path }}/saml/sso/metadata"