---

# inputs:
# _apigateway_search_types_list: string array of object types to search
# Types supported at time of writing:
#   "USER", "GROUP", "USERS", "GROUPS", "ACCESSPROFILES", "LDAPGROUPS", "CDSGROUPS", "ASSERTION", "APPLICATION", "API", "ALIAS", "POLICY", "POLICY_ACTION", "PLAN", "PACKAGE", "ADMINISTRATOR_SETTING", "PORTAL_GATEWAY", "OAUTH2_SCOPE_DATA", "SUBSCRIPTION", "API_DOCUMENT", "APPROVAL_CONFIGURATION", "OUTBOUND_PROXY", "PROXY_BYPASS", "URL_ALIAS", "KEYSTORE", "TRUSTSTORE", "KERBEROS_SETTING", "JNDI_PROVIDER_ALIAS", "JMS_CONNECTION_ALIAS", "JMS_TRIGGER", "WEB_SERVICE_ENDPOINT_ALIAS", "ACCESS_CONTROL_LIST", "RULE", "MICROGATEWAY_GROUPS", "GATEWAY_SCOPE", "OAUTH2MATERIALIZEDTOKEN", "TRANSACTION_EVENTS", "LIFECYCLE_EVENTS", "POLICYVIOLATION_EVENTS", "MONITOR_EVENTS", "ERROR_EVENTS", "THREATPROTECTION_EVENTS", "PERFORMANCE_METRICS", "QUOTA_USAGE", "DASHBOARD", "AUDIT_LOG", "REQUEST_RESPONSE_TRACE_SPANS", "APPLICATION_LOG", "MEDIATOR_TRACE_SPANS", "SERVER_LOG_TRACE_SPANS"
# _apigateway_search_condition: and, or
# _apigateway_search_scopes_list: array of attributeName + keyword
# _apigateway_search_responsefields_list: string array of fields to return
# returns: 
# _apigateway_search_response

- debug:
    var: "{{ item }}"
    verbosity: 1
  with_items:
    - _apigateway_search_types_list
    - _apigateway_search_condition
    - _apigateway_search_scopes_list
    - _apigateway_search_responsefields_list

- name: fail if mandatory params not specified
  fail:
    msg: "A mandatory param was not defined, cannot do anything."
  when: item is not defined
  with_items:
    - _apigateway_search_types_list
    - _apigateway_search_condition
    - _apigateway_search_scopes_list
    - _apigateway_search_responsefields_list

- include_tasks: "search_core.yml"
  vars:
    _apigateway_search_body:
      types: "{{ _apigateway_search_types_list }}"
      condition: "{{ _apigateway_search_condition }}"
      scope: "{{ _apigateway_search_scopes_list }}"
      responseFields: "{{ _apigateway_search_responsefields_list }}"
