---
  - debug: 
      msg: Begin tasks in packages/activate.yml

  - debug: var=rvar_apigateway_rest_objectid verbosity=1
  - debug: var=packages_activate verbosity=1

  - name: fail if mandatory params not specified
    fail: 
      msg: "A mandatory param was not defined, cannot do anything."
    when: item is not defined
    with_items:
      - "{{ rvar_apigateway_rest_objectid }}"
      - "{{ packages_activate }}"

######## first, let's fetch the package by id to check if it's already in the state we want

  - name: get the full object by id (returned in var rest_response_get)
    include_tasks: "packages/get.yml"

  - name: fail if expected response not there
    fail: 
      msg: "rest_response_get is not defined, something bad happened with the rest call?"
    when: rest_response_get is not defined

  - name: get the status field from the response
    set_fact:
      _apigateway_package_active: "{{ rest_response_get.active }}"
    when: rest_response_get is defined

  - debug: var=_apigateway_package_active verbosity=1

######## perform the operation if needed

  - name: Activate the package if flag active = true
    block:

      - name: Activate the package
        uri:
          url: "{{ apigateway_rest_packages_api }}/{{ rvar_apigateway_rest_objectid }}/activate"
          method: PUT
          user: "{{ apigateway_rest_login_username }}"
          password: "{{ apigateway_rest_login_password }}"
          return_content: yes
          force_basic_auth: yes
          validate_certs: "{{ not ( apigateway_rest_no_check_certs | default() | bool ) }}"
          status_code: [200, 201]
          timeout: 30
          headers:
            Content-Type: application/json
        register: rest_packages_activate_response

      - name: Response
        debug: var=rest_packages_activate_response verbosity=1

    when: _apigateway_package_active | bool == false and packages_activate | bool == true
  
  - debug: 
      msg: Requesting to activate the package, but it's already active...ignoring!
    when: _apigateway_package_active | bool == true and packages_activate | bool == true

  - name: Deactivate the package if flag active = false or does not exist
    block:

      - name: Deactivate the package
        uri:
          url: "{{ apigateway_rest_packages_api }}/{{ rvar_apigateway_rest_objectid }}/deactivate"
          method: PUT
          user: "{{ apigateway_rest_login_username }}"
          password: "{{ apigateway_rest_login_password }}"
          return_content: yes
          force_basic_auth: yes
          validate_certs: "{{ not ( apigateway_rest_no_check_certs | default() | bool ) }}"
          status_code: [200, 201]
          timeout: 30
          headers:
            Content-Type: application/json
        register: rest_packages_activate_response

      - name: Response
        debug: var=rest_packages_activate_response verbosity=1

    when: _apigateway_package_active | bool == true and packages_activate | bool == false
  
  - debug: 
      msg: Requesting to de-activate the package, but it's already inactive...ignoring!
    when: _apigateway_package_active | bool == false and packages_activate | bool == false
