---

  - debug: var=rvar_apigateway_rest_objectid verbosity=1
  
  - name: fail if mandatory params not specified
    fail: 
      msg: "A mandatory param was not defined, cannot do anything."
    when: item is not defined
    with_items:
      - "{{ rvar_apigateway_rest_objectid }}"

  - name: Get package by id
    uri:
      url: "{{ apigateway_rest_packages_api }}/{{ rvar_apigateway_rest_objectid }}"
      method: GET
      user: "{{ apigateway_rest_login_username }}"
      password: "{{ apigateway_rest_login_password }}"
      return_content: yes
      force_basic_auth: yes
      validate_certs: "{{ not ( apigateway_rest_no_check_certs | default() | bool ) }}"
      status_code: [200]
      body_format: json
      timeout: 30
    register: rest_response_obj

  - name: Print response
    debug:
      var: rest_response_obj
      verbosity: 1

  - name: Set response to custom var
    set_fact:
      rest_response_get: "{{ rest_response_obj.json.packageResponse | to_json }}"
