---

## TODO??

  - name: Groups to update
    debug: var=rvar_apigateway_groups_list verbosity=1

  - name: Include group tasks
    include_tasks: "do_set-groups-single.yml"
    with_items: "{{ rvar_apigateway_groups_list }}"
    loop_control:
      loop_var: rvar_apigateway_usermgt_group_single