---

  - debug: 
      msg: Begin tasks in do_activate-packages-single.yml

  - debug: var=rvar_apigateway_packages_single verbosity=1

  - name: fail if mandatory params not specified
    fail: 
      msg: "A mandatory param was not defined, cannot do anything."
    when: item is not defined
    with_items:
      - "{{ rvar_apigateway_packages_single.name }}"
      - "{{ rvar_apigateway_packages_single.version }}"
      - "{{ rvar_apigateway_packages_single.active }}"
  
  - name: First create a main variables for the package id
    set_fact:
      _apigateway_package_id: "{{ rvar_apigateway_packages_single.id | default('',true) }}"

######## fetch the main object ID if it's not already in the payload

  - debug: 
      msg: Fetching the package ID if it's not already in the payload

  - name: Get object id if it's not already in the payload
    block:

      - name: get the id based on the filter (returned in var rest_response_object_id)
        include_tasks: "packages/find-single-id.yml"
        vars:
          rvar_object_filter:
            name: "{{ rvar_apigateway_packages_single.name }}"
            version: "{{ rvar_apigateway_packages_single.version }}"

      - name: Merge the id into the object to save
        set_fact:
          _apigateway_package_id: "{{ rest_response_object_id }}"
        when: rest_response_object_id is defined and rest_response_object_id != ""

    when: rvar_apigateway_packages_single.id is not defined or rvar_apigateway_packages_single.id == ""

########## activate package or not
  
  - name: activate or de-activate the package as requested in the update object
    include_tasks: "packages/activate.yml"
    vars:
      rvar_apigateway_rest_objectid: "{{ _apigateway_package_id }}"
      packages_activate: "{{ rvar_apigateway_packages_single.active }}"

  - debug: 
      msg: End tasks in do_activate-packages-single.yml