---

  - debug: 
      msg: Begin tasks in do_set-localauthserver.yml

  - debug: var=rvar_apigateway_localauthserver verbosity=1
  
  - name: fail if mandatory params not specified
    fail: 
      msg: "A mandatory param was not defined, cannot do anything."
    when: item is not defined
    with_items:
      - "{{ rvar_apigateway_localauthserver }}"

  # Get the local auth server details (returns rest_response_object_id and rest_response_object )
  - include_tasks: "aliases/get_localauth.yml"

  - name: Create the initial update dictionary
    set_fact:
      _apigateway_current_alias: "{{ rest_response_object.alias }}"

  - name: Overwrite the existing object with the new values to update (patching)
    set_fact:
      _localauthserver_toupdate: "{{ _apigateway_current_alias | combine(rvar_apigateway_localauthserver,recursive=True) }}"

  - debug: var=_localauthserver_toupdate verbosity=1

  # Update the local auth server
  - include_tasks: "aliases/update.yml"
    vars:
      rvar_apigateway_alias_id: "{{ rest_response_object_id }}"
      rvar_apigateway_alias_toupdate: "{{ _localauthserver_toupdate }}"

  - debug: 
      msg: End tasks in do_set-localauthserver.yml
