---

  - debug: 
      msg: Begin tasks in do_set-alias-single.yml

  - debug: var=rvar_apigateway_alias_single verbosity=1
  
  - name: fail if mandatory params not specified
    fail: 
      msg: "A mandatory param was not defined, cannot do anything."
    when: item is not defined
    with_items:
      - "{{ rvar_apigateway_alias_single }}"
      - "{{ rvar_apigateway_alias_single.name }}"
      - "{{ rvar_apigateway_alias_single.type }}"

  - name: First, get the alias id based on the alias names (returned in var rest_response_object_id)
    include_tasks: "aliases/find_single_id.yml"
    vars:
      rvar_object_filter:
        name: "{{ rvar_apigateway_alias_single.name }}"
        type: "{{ rvar_apigateway_alias_single.type }}"
        stage: "{{ rvar_apigateway_alias_single.stage | default('NULL') }}"

  - name: Update the existing alias if it existed
    block:

      # Get the existing alias (returns rest_response_object_id and rest_response_object )
      - include_tasks: "aliases/get.yml"
        vars:
          rvar_apigateway_alias_id: "{{ rest_response_object_id }}"

      - name: Create the initial update dictionary
        set_fact:
          _apigateway_current_alias: "{{ rest_response_object.alias }}"

      - name: Overwrite the existing object with the new values to update (patching)
        set_fact:
          _apigateway_alias_toupdate: "{{ _apigateway_current_alias | combine(rvar_apigateway_alias_single,recursive=True) }}"

      - debug: var=_apigateway_alias_toupdate verbosity=1

      # Update the local auth server
      - include_tasks: "aliases/update.yml"
        vars:
          rvar_apigateway_alias_id: "{{ rest_response_object_id }}"
          rvar_apigateway_alias_toupdate: "{{ _apigateway_alias_toupdate }}"

    when: rest_response_object_id is defined and rest_response_object_id != ""

  - name: Create a new alias if it does not exist
    block:

      # Update the local auth server
      - include_tasks: "aliases/create.yml"
        vars:
          rvar_apigateway_alias_tocreate: "{{ rvar_apigateway_alias_single }}"

    when: rest_response_object_id is not defined or rest_response_object_id == ""

  - debug: 
      msg: End tasks in do_set-alias-single.yml