---

  - name: Users to add/update
    debug: var=rvar_apigateway_usermgt_users verbosity=1

  - name: Include group tasks
    include_tasks: "do_set-users-single.yml"
    with_items: "{{ rvar_apigateway_usermgt_users }}"
    loop_control:
      loop_var: rvar_apigateway_usermgt_user_single