---

  - name: Access profile to add/update
    debug: var=rvar_apigateway_usermgt_accessprofiles verbosity=1

  - name: Include group tasks
    include_tasks: "do_set-accessprofiles-single.yml"
    with_items: "{{ rvar_apigateway_usermgt_accessprofiles }}"
    loop_control:
      loop_var: rvar_apigateway_usermgt_accessprofile_single