---

  - name: Ports to update
    debug: var=rvar_apigateway_ports_list verbosity=1

  - name: Include Update ports tasks
    include_tasks: "do_set-ports-single.yml"
    with_items: "{{ rvar_apigateway_ports_list }}"
    loop_control:
      loop_var: rvar_apigateway_port