---

  - debug: var=rvar_apigateway_usermgt_user_single verbosity=1

  - name: First, get the user ids based on the input names (returned in var rest_response_user_ids)
    include_tasks: "users/get-users-ids-by-loginids.yml"
    vars:
      rvar_apigateway_usermgt_user_loginids: 
        - "{{ rvar_apigateway_usermgt_user_single.loginId }}"

  - name: Update the existing user if it existed
    block:

      - name: get the existing user before updating it
        uri:
          url: "{{ apigateway_rest_users_api }}/{{ rest_response_user_ids | first }}"
          method: GET
          user: "{{ apigateway_rest_login_username }}"
          password: "{{ apigateway_rest_login_password }}"
          return_content: yes
          force_basic_auth: yes
          validate_certs: "{{ not ( apigateway_rest_no_check_certs | default() | bool ) }}"
          status_code: [200, 201]
          body_format: json
          timeout: 30
        register: rest_response_get
      
      - name: Print response
        debug:
          var: rest_response_get.json
          verbosity: 1

      - name: Merge the existing user content with the updated content
        set_fact:
          rvar_apigateway_usermgt_user_single_toupdate: "{{ rest_response_get.json.users[0] | combine(rvar_apigateway_usermgt_user_single,recursive=True) }}"

      - name: Update the existing user
        uri:
          url: "{{ apigateway_rest_users_api }}/{{ rvar_apigateway_usermgt_user_single_toupdate.id }}"
          method: PUT
          user: "{{ apigateway_rest_login_username }}"
          password: "{{ apigateway_rest_login_password }}"
          return_content: yes
          body: "{{ rvar_apigateway_usermgt_user_single_toupdate | to_json }}"
          force_basic_auth: yes
          validate_certs: "{{ not ( apigateway_rest_no_check_certs | default() | bool ) }}"
          status_code: [200, 201]
          body_format: json
          timeout: 30
        register: rest_response_mutate_update
        
      - name: Response for new updated user
        debug: var=rest_response_mutate_update verbosity=1

    when: rest_response_user_ids is defined and rest_response_user_ids | length > 0

  - name: Create the user if it does not exist
    block:

      - name: Create a new user
        uri:
          url: "{{ apigateway_rest_users_api }}"
          method: POST
          user: "{{ apigateway_rest_login_username }}"
          password: "{{ apigateway_rest_login_password }}"
          return_content: yes
          body: "{{ rvar_apigateway_usermgt_user_single | default({}) | to_json }}"
          force_basic_auth: yes
          validate_certs: "{{ not ( apigateway_rest_no_check_certs | default() | bool ) }}"
          status_code: [200, 201]
          body_format: json
          timeout: 30
        register: rest_response_mutate_create

      - name: Response for new created user
        debug: var=rest_response_mutate_create verbosity=1

    when: rest_response_user_ids is not defined or rest_response_user_ids | length == 0