---

  - name: Ports to update
    debug: var=rvar_apigateway_keystore_list verbosity=1

  - name: Include Single keystore tasks
    include_tasks: "do_upload-keystore-single"
    with_items: "{{ rvar_apigateway_keystore_list }}"
    loop_control:
      loop_var: rvar_apigateway_keystore_item