---

## get the hosts of the ignite peers
- import_role:
    name: get-inventory-hosts
  vars:
    inventory_pattern: "{{ rvar_apigateway_ignitepeers_conect_inventory_pattern }}"
    inventory_hosts_property: "ansible_host"
    inventory_hosts_clear_first: true

- name: Set out facts
  set_fact:
    _ignite_peers: "{{ output_inventory_hosts }}"

- debug: var=_ignite_peers verbosity=1

- name: fail if resulting list not defined or empty
  fail:
    msg: "_ignite_peers empty...should not be at this point"
  when: _ignite_peers is not defined or (_ignite_peers | length == 0)

- name: format the list of host with the expected stuff
  set_fact:
    rvar_apigateway_ignitepeers_conect_string: "{{ _ignite_peers | join(',') }}"
