---

  - debug: var=rvar_external_elasticsearch_hosts_list verbosity=1
  - debug: var=rvar_external_elasticsearch_port verbosity=1

  - name: fail if list of elastic hosts not specified
    fail: 
      msg: "rvar_external_elasticsearch_hosts_list not specified...cannot do anything."
    when: rvar_external_elasticsearch_hosts_list is not defined or (rvar_external_elasticsearch_hosts_list | length == 0)

  - name: fail if port not defined
    fail: 
      msg: "rvar_external_elasticsearch_port not specified...cannot do anything."
    when: rvar_external_elasticsearch_port is not defined

  - name: format the list of host with the expected stuff
    set_fact:
      _external_elasticsearch_hosts: "{{ _external_elasticsearch_hosts | default([]) }} + [ '{{ _elasticsearch_host_item }}:{{ rvar_external_elasticsearch_port }}' ]"
    with_items: "{{ rvar_external_elasticsearch_hosts_list }}"
    loop_control:
      loop_var: _elasticsearch_host_item

  - debug: var=_external_elasticsearch_hosts verbosity=1

  - name: fail if resulting list not defined or empty
    fail: 
      msg: "_external_elasticsearch_hosts empty...should not be at this point"
    when: _external_elasticsearch_hosts is not defined or (_external_elasticsearch_hosts | length == 0)

  - name: Set external internaldatastore url in the right file if host list is not empty
    block:

      - name: "Update config file {{ apigateway_elasticsearch_config_file }}"
        lineinfile:
          path: "{{ apigateway_elasticsearch_config_file }}"
          regexp: '^{{ item.key }}'
          insertafter: '^#{{ item.key }}'
          line: "{{ item.key }}={{ item.value }}"
        with_dict:
          pg.gateway.elasticsearch.autostart: "false"
          pg.gateway.elasticsearch.hosts: "{{ _external_elasticsearch_hosts | join(',') }}"

      - name: Clear the _external_elasticsearch_hosts list
        set_fact:
          _external_elasticsearch_hosts: []

    when: _external_elasticsearch_hosts is defined and (_external_elasticsearch_hosts|length > 0)