---

  - debug: var=rvar_configapigateway_externalconfigs verbosity=1
  - debug: var=rvar_apidatastore_connect_string verbosity=1
  - debug: var=rvar_terracotta_connect_string verbosity=1
  - debug: var=rvar_ignite_connect_string verbosity=1

  - name: Set changed flag to false if not defined
    set_fact: 
      configure_apigateway_set_externalconfigs_changed: false
    when: configure_apigateway_set_externalconfigs_changed is not defined
    
  - name: fail if external config structure is not defined
    fail: 
      msg: "rvar_configapigateway_externalconfigs not specified...cannot do anything."
    when: rvar_configapigateway_externalconfigs is not defined

  - name: fail if external config structure does not have apigw 1st child
    fail: 
      msg: "rvar_configapigateway_externalconfigs.apigw not specified...cannot do anything."
    when: rvar_configapigateway_externalconfigs.apigw is not defined

  - name: fail if both terracotta and ignite server connect string were provided
    fail: 
      msg: "Both Terracotta and Ignote connect strings were provided... not possible, pick one!!"
    when: rvar_ignite_connect_string is defined and (rvar_ignite_connect_string | length > 0) and rvar_terracotta_connect_string is defined and (rvar_terracotta_connect_string | length > 0)

  - name: update external config with elastic hostnames
    set_fact:
      rvar_configapigateway_externalconfigs: "{{ rvar_configapigateway_externalconfigs | combine({'apigw': {'elasticsearch': {'hosts': rvar_apidatastore_connect_string }}}, recursive=True) }}"
    when: rvar_apidatastore_connect_string is defined and (rvar_apidatastore_connect_string | length > 0)
    
  - name: update external config with ignite hostnames
    block:

      - name: add default clustering block if it's not there
        set_fact:
          rvar_configapigateway_externalconfigs: "{{ rvar_configapigateway_externalconfigs | combine(apigateway_external_configs_template_clustering_ignite, recursive=True) }}"
        when: rvar_configapigateway_externalconfigs.apigw.cluster is not defined

      - name: update key for elastic search
        set_fact:
          rvar_configapigateway_externalconfigs: "{{ rvar_configapigateway_externalconfigs | combine({'apigw': {'cluster': {'ignite': {'hostnames': rvar_ignite_connect_string }}}}, recursive=True) }}"
    
    when: rvar_ignite_connect_string is defined and (rvar_ignite_connect_string | length > 0)
  
  - name: update external config with terracotta hostnames
    block:
      
      - name: add default clustering block if it's not there
        set_fact:
          rvar_configapigateway_externalconfigs: "{{ rvar_configapigateway_externalconfigs | combine(apigateway_external_configs_template_clustering_terracotta, recursive=True) }}"
        when: rvar_configapigateway_externalconfigs.apigw.cluster is not defined

      - name: update key for elastic search
        set_fact:
          rvar_configapigateway_externalconfigs: "{{ rvar_configapigateway_externalconfigs | combine({'apigw': {'cluster': {'tsaUrls': rvar_terracotta_connect_string }}}, recursive=True) }}"
    
    when: rvar_terracotta_connect_string is defined and (rvar_terracotta_connect_string | length > 0)

  - name: Create apigateway_externalconfigs only if value variable is not empty
    block:

      - name: Creating custom external config file
        copy:
          dest: "{{ apigateway_external_configs_file_path }}"
          content: "{{ rvar_configapigateway_externalconfigs | to_nice_yaml(indent=4,width=500) }}"
        register: custom_external_configs_update

      - name: Create the config-sources content
        set_fact: 
          configure_apigateway_config_sources_content:
            sources:
              - type: YAML
                allowEdit: true
                properties:
                  location: "{{ apigateway_external_configs_file_path }}"

      - name: Updating / Creating custom config-sources file
        copy:
          dest: "{{ apigateway_external_configs_source_file_path }}"
          content: "{{ configure_apigateway_config_sources_content | to_nice_yaml(indent=4,width=500) }}"
        register: "custom_config_sources_update"

      - name: Set changed flag to true if any mutating operation did change
        set_fact: 
          configure_apigateway_set_externalconfigs_changed: true
        when: custom_external_configs_update.changed == true or custom_config_sources_update.changed == true

    when: rvar_configapigateway_externalconfigs is defined

  - name: Print the changed var
    debug:
      var: configure_apigateway_set_externalconfigs_changed
      verbosity: 2