---

  - debug: var=rvar_external_elasticsearch_hosts_list verbosity=1
  - debug: var=rvar_external_elasticsearch_proto verbosity=1
  - debug: var=rvar_external_elasticsearch_port verbosity=1

  - name: fail if list of elastic hosts not specified
    fail: 
      msg: "rvar_external_elasticsearch_hosts_list not specified...cannot do anything."
    when: rvar_external_elasticsearch_hosts_list is not defined or (rvar_external_elasticsearch_hosts_list | length == 0)

  - name: fail if port not defined
    fail: 
      msg: "rvar_external_elasticsearch_port not specified...cannot do anything."
    when: rvar_external_elasticsearch_port is not defined

  - name: format the list of host with the expected stuff
    set_fact:
      _external_elasticsearch_hosts: "{{ _external_elasticsearch_hosts | default([]) }} + [ '{{ rvar_external_elasticsearch_proto }}://{{ _elasticsearch_host_item }}:{{ rvar_external_elasticsearch_port }}' ]"
    with_items: "{{ rvar_external_elasticsearch_hosts_list }}"
    loop_control:
      loop_var: _elasticsearch_host_item

  - debug: var=_external_elasticsearch_hosts verbosity=1

  - name: fail if resulting list not defined or empty
    fail: 
      msg: "_external_elasticsearch_hosts empty...should not be at this point"
    when: _external_elasticsearch_hosts is not defined or (_external_elasticsearch_hosts | length == 0)

  - name: Set external elastic search in the right file 
    block:

      - name: "Update config file {{ apigateway_ui_configuration_config_file }}"
        lineinfile:
          path: "{{ apigateway_ui_configuration_config_file }}"
          regexp: '^{{ item.key }}'
          insertafter: '^#{{ item.key }}'
          line: "{{ item.key }}={{ item.value }}"
        with_dict:
          apigw.es.url: "{{ _external_elasticsearch_hosts | join(',') }}"

      #### second update: kibana yml file
      - name: Get content of elastic search config
        shell: "cat {{ apigateway_kibana_config_file }}"
        register: kibana_config_yml
      
      - name: Print the raw elasticsearch config
        debug:
          var: kibana_config_yml.stdout_lines
          verbosity: 1

      - set_fact:
          kibana_config: "{{ kibana_config_yml.stdout | from_yaml }}"

      - name: Print the ingested kibana_config
        debug:
          var: kibana_config
          verbosity: 1

      - name: Print elasticsearch.hosts from the config
        debug:
          msg: "Looking at item: {{ kibana_config['elasticsearch.hosts'] }}"
          verbosity: 1

      - name: Change kibana elasticsearch.hosts value to the list of hosts
        set_fact:
          content_yml: "{{ kibana_config | combine({'elasticsearch.hosts': _external_elasticsearch_hosts}, recursive=True) }}"

      - name: Print the updated content
        debug: 
          var: content_yml
          verbosity: 1
    
      - name: Write the updated content back to the same YAML file.
        template:
          src: yaml_content.yml.j2
          dest: "{{ apigateway_kibana_config_file }}"
          backup: yes
      
      - name: Clear the _external_elasticsearch_hosts list
        set_fact:
          _external_elasticsearch_hosts: []

    when: _external_elasticsearch_hosts is defined and (_external_elasticsearch_hosts|length > 0)